### ISSUE TITLE
Prevent Users From Opening Files?

### ISSUE THREAD

**Issue by freepicheep** [triumphantomato/cryptsidian#5]
This is a feature request. But first, thanks for putting time into making a great plugin!

Is it possible to prevent users from opening files when the vault is encrypted? This would be nice to prevent accidental corruption of files. If so, would it also be possible to change the css for the start-up page to display a message that the vault is encrypted with a shortcut button to decrypt the vault? If these features could be added, this plugin would be even better.

**Comment by triumphantomato** [comment]
Hi @aCodingLegolas , thank you for the kind feedback! Glad you are finding this plugin helpful.

Your idea is a good one and I considered it, but ultimately decided against implementing it. In order to implement it, the plugin needs to save some state that knows if the user has encrypted their files or not.

So the problem becomes - how to save this state? What I thought of was saving the state in an independent file in the vault, for example `cryptsidian.locked`. The problem is, if this file is not written to properly, Cryptsidian could provide the user with the wrong prompt.

For example, suppose you have your vault saved in a Dropbox folder, and Dropbox is synching in the background when you open your vault. Is there a risk of an old `cryptsidian.locked` file being visible to the plugin, and the plugin suggesting the user decrypt when they haven't actually encrypted yet? 

If the user then presses the button and runs the decrypt routine on non-encrypted data, the data is kind of borked and recovery is difficult.

There might be a better way to do this, but I'm not aware.

**Comment by mortal1** [comment]
I have a solution for the problem of incorrectly decrypting files.

Before Encrypting
- append a string to the end of the file such as "cryptsidian encrypted"

After Decrypting
- check that the file ends with the string "cryptsidian encrypted". 
  - If it does not, then undo the decryption and report the error to the user
  - if it does, then remove the string.
